# Generated by Django 4.2.19 on 2025-03-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nif', models.CharField(max_length=8)),
                ('direccio', models.CharField(max_length=100)),
                ('poblacio', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('pais', models.CharField(max_length=100)),
                ('registre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('jerarquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botiga.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cistell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contadors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(max_length=10, unique=True)),
                ('qty', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('botiga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='botiga.botiga')),
                ('cistell', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='botiga.cistell')),
            ],
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('percentatge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodePagament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=20)),
                ('descripcio', models.CharField(max_length=150)),
                ('iva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='botiga.iva')),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('cognom', models.CharField(max_length=50)),
                ('cognom2', models.CharField(max_length=50)),
                ('pswd', models.CharField(max_length=10)),
                ('direccio', models.CharField(max_length=100)),
                ('poblacio', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('preu', models.FloatField()),
                ('dto', models.FloatField(null=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.producte')),
            ],
        ),
        migrations.CreateModel(
            name='TallaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.talla')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.variant')),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('preu', models.FloatField()),
                ('dto', models.FloatField(null=True)),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.factura')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='botiga.talla')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='botiga.variant')),
            ],
        ),
        migrations.CreateModel(
            name='LineaCistell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cistell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.cistell')),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.tallavariant')),
            ],
        ),
        migrations.CreateModel(
            name='Imatges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.variant')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='pagament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='botiga.metodepagament'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='botiga.contadors'),
        ),
        migrations.CreateModel(
            name='Enviament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dies_min', models.IntegerField()),
                ('dies_max', models.IntegerField(null=True)),
                ('cost', models.FloatField()),
                ('preu_min', models.FloatField(null=True)),
                ('iva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='botiga.iva')),
            ],
        ),
        migrations.AddField(
            model_name='cistell',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='botiga.user'),
        ),
        migrations.AddField(
            model_name='cistell',
            name='enviament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='botiga.enviament'),
        ),
        migrations.CreateModel(
            name='CatProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.categoria')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.producte')),
            ],
        ),
    ]
