# Generated by Django 5.1.6 on 2025-02-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('jerarquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botiga.categoria')),
            ],
        ),
    ]
