# Generated by Django 4.2.19 on 2025-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacistell',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
