# Generated by Django 4.2.19 on 2025-04-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0002_lineacistell_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cistell',
            name='enviament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='botiga.enviament'),
        ),
    ]
