# Generated by Django 4.2.19 on 2025-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0004_remove_cistell_enviament_cistell_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ivaEnviament',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='factura',
            name='totalFra',
            field=models.FloatField(default=0.0),
        ),
    ]
