# Generated by Django 4.2.19 on 2025-04-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0005_factura_ivaenviament_factura_totalfra'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botiga.factura')),
            ],
        ),
    ]
