# Generated by Django 4.2.19 on 2025-04-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0006_ivafactura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ivafactura',
            old_name='iva',
            new_name='tipusiva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='ivaEnviament',
        ),
    ]
