# Generated by Django 4.2.19 on 2025-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0008_alter_lineafactura_talla_alter_lineafactura_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='gtoEnvio',
            field=models.FloatField(default=0.0),
        ),
    ]
