# Generated by Django 4.2.19 on 2025-04-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0010_remove_factura_gtoenvio_remove_lineafactura_talla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineafactura',
            name='nom',
        ),
    ]
