# Generated by Django 4.2.19 on 2025-04-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0011_remove_lineafactura_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nif',
            field=models.CharField(default='47107398L', max_length=9),
            preserve_default=False,
        ),
    ]
