# Generated by Django 4.2.19 on 2025-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botiga', '0012_user_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='gtoEnvio',
            field=models.FloatField(default=0.0),
        ),
    ]
